services:
  untis-proxy:
    image: datpersothere/untis-proxy:latest
    container_name: untis-proxy
    restart: unless-stopped
    ports:
      - "8509:8509"
    environment:
      UNTIS_ADDR: ":8509"
      UNTIS_ENV: "prod"
      UNTIS_VERSION: "v1.2.0"
      UNTIS_POLL_INTERVAL: "60s"
    volumes:
      - ./data:/data
    labels:
      - dockflare.enable=true
      - dockflare.hostname=api-untis.deelabs.tech
      - dockflare.service=http://untis-proxy:8509
